name: Studio4
favicon: null
layout_spectrum: 0.25806
typography_spectrum: 0.39515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0f19'
    - '#e1dad3'
    - '#47484f'
    - '#ca9e85'
    - '#4695f1'
  brandStrength: 0.8672402070369571
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
