name: Studio4
favicon: null
layout_spectrum: 0.74462
typography_spectrum: 0.75832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#b39758'
    - '#ffffff'
    - '#493a2a'
    - '#706239'
  brandStrength: 0.8672402070369571
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
