name: Studio4
favicon: null
layout_spectrum: 0.29817458847537637
typography_spectrum: 0.44381365762092173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ab925f'
    - '#ffffff'
    - '#d5cbb3'
    - '#686867'
  brandStrength: 0.8672402070369571
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
